const fs = require('node:fs');
const path = require('node:path');
const target = path.join(__dirname, '../supabase/functions/ami-api/generated');
fs.mkdirSync(target, {recursive:true});
for (const name of ['read','admin','workflow','system','import-export']) {
  let source = fs.readFileSync(path.join(__dirname, `../local-${name}.js`), 'utf8');
  source = source.replace(/const crypto = require\('node:crypto'\);/, "import crypto from 'node:crypto';");
  source = source.replace(/const XLSX = require\('xlsx'\);/, "import * as XLSX from 'npm:xlsx@0.18.5';\nimport {Buffer} from 'node:buffer';");
  source = source.replace(/const (\w+) = require\('\.\/local-([^']+)'\);/g, "import * as $1 from './$2.mjs';");
  source = source.replace(/module\.exports\s*=\s*\{([^}]+)\};?/, 'export {$1};');
  fs.writeFileSync(path.join(target, `${name}.mjs`), '// Generated by scripts/build-edge.js; edit the shared local service.\n' + source);
}
// Package only the read functions from Apps Script in a request-local lexical scope.
// Their write/Drive functions are never exposed as RPC handlers.
const sources = ['Config.gs','AdminService.gs','Code.gs','ImportExportService.gs'].map(file => fs.readFileSync(path.join(__dirname, '..', file), 'utf8')).join('\n');
const wrapper = `export async function readDashboard(pool, schema, method, user) {
  const names = ['SETTINGS','AMI_CYCLE','AMI_AUDITI','AMI_TEAM','AMI_STANDARD_ASSIGN','SELF_EVAL','DESK_EVAL','FINDINGS','REPORT_LOG','MASTER_STANDAR','MASTER_PRODI','MASTER_UNIT','MASTER_AUDITOR','MASTER_PIMPINAN'];
  const results = await Promise.all(names.map(name => pool.query('SELECT * FROM "ami"."' + name + '"')));
  const data = Object.fromEntries(names.map((name, i) => [name, results[i].rows]));
  const cleanText_ = value => String(value ?? '').trim();
  const normalizeUsername_ = value => cleanText_(value).toLowerCase();
  const getAllRows_ = name => data[name] || [];
  const getSetting_ = (key, fallback) => (data.SETTINGS.find(row => row.Key === key) || {}).Value || fallback;
  const findOne_ = (name, key, value) => getAllRows_(name).find(row => row[key] === value);
  const bool_ = value => value === true || ['true','1','yes'].includes(cleanText_(value).toLowerCase());
  const cleanRow_ = row => ({...row});
  const serializeValue_ = value => JSON.parse(JSON.stringify(value));
  const now_ = () => new Date().toISOString();
  const session_ = () => user;
  const publicUser_ = row => ({userId:row.UserID,username:row.Username,nama:row.Nama,role:row.Role,refType:row.RefType || '',refId:row.RefID || '',forceChangePassword:bool_(row.ForceChangePassword)});
  const CacheService = {getScriptCache: () => ({get: () => null, put: () => {}})};
  ${sources}
  const methods = {getBootstrap,getExecutiveDashboard,getPublicExecutiveDashboard,getImportExportCatalog,getPublicAppInfo};
  if (!Object.hasOwn(methods, method)) throw new Error('Metode dashboard tidak dikenal.');
  return methods[method]();
}`;
fs.writeFileSync(path.join(target,'dashboard.mjs'), '// Generated read-only Apps Script adapter.\n'+wrapper);
